name: Token Auto Refresh Threads

on:
  schedule:
    - cron: '0 0 */49 * *' # Otomatis tiap 50 hari
  workflow_dispatch: # Bisa klik manual dari tab Actions

jobs:
  refresh:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      secrets: write
      
    steps:
      - name: Checkout repo
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 1
          persist-credentials: true

      - name: '2. Setup Bun.js'
        uses: oven-sh/setup-bun@3d267786b128fe76c2f16a390aa2448b815359f3 # v2
        with:
          bun-version: latest

      - name: Install axios
        run: bun install
        
      - name: Get New Token
        id: refresh_token
        env:
          THREADS_ACCESS_TOKEN: ${{ secrets.THREADS_ACCESS_TOKEN }}
        run: |
          # Jalankan script yang ada di folder dapur/
          # Kita simpan outputnya ke environment variable GitHub
          NEW_TOKEN=$(bun run dapur/refresh-threads-token.ts)
          echo "NEW_THREADS_TOKEN=$NEW_TOKEN" >> $GITHUB_ENV

      - name: Update GitHub Secret
        env:
          GH_TOKEN: ${{ secrets.GH_PAT }}
        run: |
          # Update secret THREADS_ACCESS_TOKEN dengan token baru
          # Menggunakan flag --repo agar spesifik ke repo Layar Kosong
          gh secret set THREADS_ACCESS_TOKEN --body "$NEW_THREADS_TOKEN" --repo ${{ github.repository }}
