name: RenovateX

on:
  workflow_dispatch:
    inputs:
      repoCache:
        description: 'Reset atau disable cache?'
        type: choice
        default: enabled
        options:
          - enabled
          - disabled
          - reset
  schedule:
    - cron: '0 10 * * *' # 18.00 WITA

env:
  CACHE_KEY: renovate-cache-main
  CACHE_ARCHIVE: renovate_cache.tar.gz
  CACHE_DIR: /tmp/renovate/cache/renovate/repository

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4 # v4 adalah yang paling stabil saat ini

      - name: Download previous cache
        uses: dawidd6/action-download-artifact@v12
        if: github.event.inputs.repoCache != 'disabled'
        continue-on-error: true
        with:
          name: ${{ env.CACHE_KEY }}
          path: cache-download
          workflow_conclusion: success

      - name: Extract renovate cache
        run: |
          set -x
          if [ -d cache-download ] && [ "${{ github.event.inputs.repoCache }}" != "reset" ]; then
            sudo mkdir -p ${{ env.CACHE_DIR }}
            sudo tar -xzf cache-download/${{ env.CACHE_ARCHIVE }} -C ${{ env.CACHE_DIR }}
            sudo chown -R 12021:0 /tmp/renovate/
          else
            sudo mkdir -p ${{ env.CACHE_DIR }}
            sudo chown -R 12021:0 /tmp/renovate/
          fi

      - name: Run Renovate
        uses: renovatebot/github-action@v44.2.6
        with:
          configurationFile: mini/renovate.json5
          token: ${{ secrets.RENOVATE_TOKEN }}
          renovate-version: full
        env:
          RENOVATE_REPOSITORIES: ${{ github.repository }}
          RENOVATE_REPOSITORY_CACHE: ${{ github.event.inputs.repoCache || 'enabled' }}

      - name: Compress renovate cache
        if: github.event.inputs.repoCache != 'disabled'
        run: |
          sudo chown -R runner:docker ${{ env.CACHE_DIR }}
          tar -czvf ${{ env.CACHE_ARCHIVE }} -C ${{ env.CACHE_DIR }} .

      - name: Save cache to Artifact
        if: github.event.inputs.repoCache != 'disabled'
        uses: actions/upload-artifact@v6 # v4 jauh lebih cepat untuk file besar
        with:
          name: ${{ env.CACHE_KEY }}
          path: ${{ env.CACHE_ARCHIVE }}
          retention-days: 3
