name: RenovateX

on:
  workflow_dispatch:
  schedule:
    - cron: '0 10 * * *' # 18.00 WITA

jobs:
  renovate:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      # 1️⃣ Setup Docker Buildx (Ini kunci buat caching layer)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # 2️⃣ Gunakan cache khusus untuk Docker layer
      - name: Cache Docker layers
        uses: actions/cache@v4
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-renovate-cache-${{ github.run_id }}
          restore-keys: |
            ${{ runner.os }}-renovate-cache-

      # 3️⃣ Run Renovate
      - name: Run Renovate
        uses: renovatebot/github-action@v44.2.6
        with:
          configurationFile: mini/renovate.json5
          token: ${{ secrets.RENOVATE_TOKEN }}
          renovate-version: slim
        env:
          RENOVATE_REPOSITORIES: ${{ github.repository }}
          RENOVATE_ONBOARDING: "false"
          RENOVATE_REQUIRE_CONFIG: "ignored"
          # Cache metadata Renovate tetap pakai prefix kesukaanmu
          RENOVATE_REPOSITORY_CACHE: /tmp/renovate-cache-inline
