name: Renovate
on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 1'

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6.0.2

      # 1. Setup Docker Buildx (Ini kunci buat caching Docker)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # 1. Setup Cache (Biar proses scan berikutnya super cepat)
      - name: Cache Renovate
        uses: actions/cache@v4
        with:
          path: /tmp/renovate/cache
          # Kunci ini akan berubah kalau config renovatemu berubah
          key: ${{ runner.os }}-renovate-${{ hashFiles('**/renovate.json', '**/.renovaterc.json') }}
          restore-keys: |
            ${{ runner.os }}-renovate-

      - name: Perbaiki Izin Folder Cache
        run: |
          sudo mkdir -p /tmp/renovate/cache /tmp/renovate/repos
          sudo chmod -R 777 /tmp/renovate

      - name: Self-hosted Renovate
        uses: renovatebot/github-action@v44.2.6
        with:
          configurationFile: mini/renovate.json5 # Pastikan filenya .json atau .json5 sesuai di folder
          token: ${{ secrets.RENOVATE_TOKEN }}
        env:
          RENOVATE_REPOSITORIES: ${{ github.repository }}
          RENOVATE_REPOSITORY_CACHE_TYPE: "local" # Pakai penyimpanan lokal di runner
          RENOVATE_CACHE_DIR: /tmp/renovate/cache
          RENOVATE_ONBOARDING: "false"
          RENOVATE_REQUIRE_CONFIG: "ignored"
          RENOVATE_REPOSITORY_CACHE: "enabled"
          RENOVATE_OPTIMIZE_FOR_DISABLED: 'true'
          # Tambahan biar dia nggak bikin folder di tempat terlarang
          RENOVATE_BASE_DIR: /tmp/renovate
          RENOVATE_BINARY_SOURCE: "docker"
