name: Lint and Fix

on:
  workflow_dispatch:
  schedule:
    - cron: '0 17 28 * *'

permissions:
  contents: write
  pull-requests: write
  issues: write
  statuses: write

jobs:
  build:
    name: Lint & Create PR
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v6 # Gunakan v4 yang stabil
        with:
          fetch-depth: 0

      # --- BAGIAN CACHE MULAI DISINI ---
      - name: Cache Super-Linter Docker Image
        uses: actions/cache@v5
        with:
          path: /tmp/super-linter-image
          key: ${{ runner.os }}-super-linter-${{ github.run_id }}
          restore-keys: |
            ${{ runner.os }}-super-linter-
      # ---------------------------------

      - name: Super-linter
        uses: super-linter/super-linter@v8.3.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VALIDATE_ALL_CODEBASE: false
          # Konfigurasi linter tetap sama...
          VALIDATE_HTML_PRETTIER: true
          VALIDATE_CSS_PRETTIER: true
          VALIDATE_JAVASCRIPT_PRETTIER: true
          VALIDATE_JSON_PRETTIER: true
          VALIDATE_MARKDOWN: true
          FIX_HTML_PRETTIER: true
          FIX_CSS_PRETTIER: true
          FIX_JAVASCRIPT_PRETTIER: true
          FIX_JSON_PRETTIER: true
          VALIDATE_PYTHON_BLACK: true
          FIX_PYTHON_BLACK: true
          VALIDATE_PYTHON_RUFF: true
          VALIDATE_BASH: true
          VALIDATE_SHELL_SHFMT: true
          FIX_SHELL_SHFMT: true
          VALIDATE_PERL: true
          VALIDATE_GITLEAKS: true
          VALIDATE_TRIVY: true
          VALIDATE_YAML: true

      - name: Cleanup Output Folder
        if: always()
        run: sudo rm -rf super-linter-output

      - name: Create Pull Request with Fixes
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "chore: auto-format code with Super-Linter"
          title: "ðŸ¤– Auto-fix: Linting & Formatting"
          body: "Halo! Saya merapikan kode secara otomatis."
          branch: super-linter-fixes
          base: main
          delete-branch: true

