name: Lint and Fix

on:
  workflow_dispatch:
  schedule:
    - cron: '0 17 28 * *'

permissions:
  contents: write
  pull-requests: write
  issues: write
  statuses: write

jobs:
  build:
    name: Lint & Create PR
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # --- STRATEGI CACHE DOCKER SUPER-LINTER (LATEST) ---
      - name: Cache Super-Linter Docker Image
        id: cache-linter
        uses: actions/cache@v5
        with:
          path: ~/super-linter-image.tzst
          # Tanpa nomor versi, cukup label latest
          key: linter-cache-docker-latest 

      - name: Load or Pull Super-Linter Image
        run: |
          if [ -f ~/super-linter-image.tzst ]; then
            echo "Memulihkan image Super-Linter dengan zstd..."
            zstd -d -c -T0 ~/super-linter-image.tzst | docker load
          else
            echo "Cache miss, mendownload Super-Linter terbaru..."
            docker pull ghcr.io/super-linter/super-linter:latest
            docker save ghcr.io/super-linter/super-linter:latest | zstd -T0 -o ~/super-linter-image.tzst
          fi
      # --------------------------------------------------

      - name: Super-linter
        # Tetap pakai action terbaru tanpa pusing nomor versi
        uses: super-linter/super-linter@main 
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VALIDATE_ALL_CODEBASE: false
          # Konfigurasi linter
          VALIDATE_HTML_PRETTIER: true
          VALIDATE_CSS_PRETTIER: true
          VALIDATE_JAVASCRIPT_PRETTIER: true
          VALIDATE_JSON_PRETTIER: true
          VALIDATE_MARKDOWN: true
          FIX_HTML_PRETTIER: true
          FIX_CSS_PRETTIER: true
          FIX_JAVASCRIPT_PRETTIER: true
          FIX_JSON_PRETTIER: true
          VALIDATE_PYTHON_BLACK: true
          FIX_PYTHON_BLACK: true
          VALIDATE_PYTHON_RUFF: true
          VALIDATE_BASH: true
          VALIDATE_SHELL_SHFMT: true
          FIX_SHELL_SHFMT: true
          VALIDATE_PERL: true
          VALIDATE_GITLEAKS: true
          VALIDATE_TRIVY: true
          VALIDATE_YAML: true

      - name: Cleanup Output Folder
        if: always()
        run: sudo rm -rf super-linter-output

      - name: Create Pull Request with Fixes
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "chore: auto-format code with Super-Linter"
          title: "ü§ñ Auto-fix: Linting & Formatting"
          body: "Halo! Saya merapikan kode secara otomatis. üèùÔ∏è"
          branch: super-linter-fixes
          base: main
          delete-branch: true
