name: Renovate

on:
  workflow_dispatch:
  schedule:
    - cron: '0 11 * * *' # 18.00 WITA

jobs:
  renovate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Cache Renovate Data
        uses: actions/cache@v5
        with:
          path: /tmp/renovate/cache
          key: renovate-cache-${{ github.run_id }}
          restore-keys: |
            renovate-cache-

      - name: Prepare Renovate Directories
        run: |
          sudo mkdir -p /tmp/renovate/cache /tmp/renovate/repos
          sudo chmod -R 777 /tmp/renovate

      - name: Run Renovate
        uses: renovatebot/github-action@v44.2.6
        with:
          configurationFile: mini/renovate.json5
          token: ${{ secrets.RENOVATE_TOKEN }}
        env:
          RENOVATE_REPOSITORIES: ${{ github.repository }}
          RENOVATE_BASE_DIR: /tmp/renovate
          RENOVATE_CACHE_DIR: /tmp/renovate/cache
          RENOVATE_REPOSITORY_CACHE: "enabled"
          RENOVATE_REPOSITORY_CACHE_TYPE: "local"
          RENOVATE_ONBOARDING: "false"
          RENOVATE_REQUIRE_CONFIG: "ignored"
